In [ ]:
# 드라이브 연동
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# 전체
import numpy as np
#이전에 처리해둔 사전과 전처리 라벨링 가져옴, zip파일 형태 다운
%cd /content/
!gdown 1bewsF-RpEFRDMjRJZaidtVzl1sMhn_Sg --output audio.npy
#https://drive.google.com/file/d/1bewsF-RpEFRDMjRJZaidtVzl1sMhn_Sg/view?usp=share_link
!gdown 1g9cQhVBRI4KgaU43Wm4Oemtvpa9YXQwt --output inst.txt
# https://drive.google.com/file/d/1g9cQhVBRI4KgaU43Wm4Oemtvpa9YXQwt/view?usp=share_link
# 배열 로드

/content
Downloading...
From: https://drive.google.com/uc?id=1bewsF-RpEFRDMjRJZaidtVzl1sMhn_Sg
To: /content/audio.npy
100% 6.78G/6.78G [00:58<00:00, 116MB/s]
Downloading...
From: https://drive.google.com/uc?id=1g9cQhVBRI4KgaU43Wm4Oemtvpa9YXQwt
To: /content/inst.txt
100% 33.9k/33.9k [00:00<00:00, 87.6MB/s]


In [ ]:
# 500000기준

# 전체
import numpy as np
#이전에 처리해둔 사전과 전처리 라벨링 가져옴, zip파일 형태 다운
%cd /content/
!gdown 1JvViQGIgZ51k8XPACKLRp6Q4mbXtIIfZ --output audio.npy
#https://drive.google.com/file/d/1JvViQGIgZ51k8XPACKLRp6Q4mbXtIIfZ/view?usp=share_link
!gdown 1xGp1_MboRWQOGwQBH3R_M41mu-wGXP31 --output inst.txt
#https://drive.google.com/file/d/1xGp1_MboRWQOGwQBH3R_M41mu-wGXP31/view?usp=share_link
# 배열 로드

/content
Downloading...
From: https://drive.google.com/uc?id=1JvViQGIgZ51k8XPACKLRp6Q4mbXtIIfZ
To: /content/audio.npy
100% 6.77G/6.77G [01:14<00:00, 90.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1xGp1_MboRWQOGwQBH3R_M41mu-wGXP31
To: /content/inst.txt
100% 67.7k/67.7k [00:00<00:00, 126MB/s]


In [2]:
#부분
import numpy as np
#이전에 처리해둔 사전과 전처리 라벨링 가져옴, zip파일 형태 다운
%cd /content/
!gdown 1-13_ADzk3fWJt4ZoVXpT5Vu2-4HTbt_Z --output audio.npy
# https://drive.google.com/file/d/1-13_ADzk3fWJt4ZoVXpT5Vu2-4HTbt_Z/view?usp=share_link
!gdown 1mifYHOsThNQhg_T-1xKtkgm66CJQfdYZ --output inst.txt
# https://drive.google.com/file/d/1mifYHOsThNQhg_T-1xKtkgm66CJQfdYZ/view?usp=share_link

/content
Downloading...
From: https://drive.google.com/uc?id=1-13_ADzk3fWJt4ZoVXpT5Vu2-4HTbt_Z
To: /content/audio.npy
100% 52.4M/52.4M [00:00<00:00, 182MB/s]
Downloading...
From: https://drive.google.com/uc?id=1mifYHOsThNQhg_T-1xKtkgm66CJQfdYZ
To: /content/inst.txt
100% 3.25k/3.25k [00:00<00:00, 19.4MB/s]


In [ ]:
audio_np = np.load('/content/audio.npy', allow_pickle=True)

In [ ]:
print(audio_np.shape)
data = np.vstack(audio_np)
print(data.shape)

(3385, 500000)
(3385, 500000)


In [ ]:
print(data[0])
print(audio_np[0])

[-7.2759576e-12  3.6379788e-12 -1.0913936e-11 ... -1.6483910e-02
 -2.3655213e-02 -3.0082997e-02]
[-7.2759576e-12  3.6379788e-12 -1.0913936e-11 ... -1.6483910e-02
 -2.3655213e-02 -3.0082997e-02]


In [ ]:
print(data.shape)

(3385, 500000)


In [ ]:
import librosa
audio_np = np.load('/content/audio.npy', allow_pickle=True)
sr = 22050
audio_mfcc = []
for y in audio_np:
    ret = librosa.feature.mfcc(y=y,sr=sr)
    audio_mfcc.append(ret)

In [ ]:

audio_mfcc = np.array(audio_mfcc)

In [ ]:
np.save('/content/mfcc_500000.npy', audio_mfcc)

In [ ]:
from google.colab import files
files.download(f'/content/mfcc_500000.npy')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

여기서부터 시작

In [ ]:
# 전체
import numpy as np
#이전에 처리해둔 사전과 전처리 라벨링 가져옴, zip파일 형태 다운
%cd /content/
!gdown 1WOKPSWY345IB6IU8R1BNkzEs5xNkhNsx --output mfcc.npy
#https://drive.google.com/file/d/1WOKPSWY345IB6IU8R1BNkzEs5xNkhNsx/view?usp=share_link
!gdown 1g9cQhVBRI4KgaU43Wm4Oemtvpa9YXQwt --output inst.txt
# https://drive.google.com/file/d/1g9cQhVBRI4KgaU43Wm4Oemtvpa9YXQwt/view?usp=share_link
# 배열 로드

/content
Downloading...
From: https://drive.google.com/uc?id=1WOKPSWY345IB6IU8R1BNkzEs5xNkhNsx
To: /content/mfcc.npy
100% 265M/265M [00:05<00:00, 44.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1g9cQhVBRI4KgaU43Wm4Oemtvpa9YXQwt
To: /content/inst.txt
100% 33.9k/33.9k [00:00<00:00, 119MB/s]


In [ ]:
# 전체
#500000으로!
import numpy as np
#이전에 처리해둔 사전과 전처리 라벨링 가져옴, zip파일 형태 다운
%cd /content/
!gdown 1z1NRSRwonwasmv_JvsfqsE8VsQnfPnU4 --output mfcc.npy
#https://drive.google.com/file/d/1z1NRSRwonwasmv_JvsfqsE8VsQnfPnU4/view?usp=share_link
!gdown 1xGp1_MboRWQOGwQBH3R_M41mu-wGXP31 --output inst.txt
#https://drive.google.com/file/d/1xGp1_MboRWQOGwQBH3R_M41mu-wGXP31/view?usp=share_link
# 배열 로드

/content
Downloading...
From: https://drive.google.com/uc?id=1z1NRSRwonwasmv_JvsfqsE8VsQnfPnU4
To: /content/mfcc.npy
100% 265M/265M [00:07<00:00, 33.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1xGp1_MboRWQOGwQBH3R_M41mu-wGXP31
To: /content/inst.txt
100% 67.7k/67.7k [00:00<00:00, 97.7MB/s]


In [ ]:
# import numpy as np

# with open('/content/inst.txt', 'r') as f:
#     lines = f.readlines()

# inst_list = []

# # 최대 열의 길이 계산
# max_length = max(len(line.strip().split()) for line in lines)

# for line in lines:
#     row = line.strip().split()  # 공백으로 분리
#     row = [int(item)+1 for item in row]  # 정수로 변환
    
#     # 열의 길이가 최대 열의 길이와 일치하도록 맞춤
#     if len(row) < max_length:
#         row += [0] * (max_length - len(row))  # 빈 값을 0으로 채움
    
#     inst_list.append(row)

# inst_array = np.array(inst_list)

# np.save('/content/inst.npy', inst_array)

In [9]:
import numpy as np

with open('/content/inst.txt', 'r') as f:
    lines = f.readlines()

inst_list = []

for line in lines:
    row = line.strip().split()  # 공백으로 분리
    base = [0] * 331
    for item in row:
      base[int(item)] = 1#/len(row)  # 정수로 변환
    
    # 열의 길이가 최대 열의 길이와 일치하도록 맞춤
    
    inst_list.append(base)

inst_array = np.array(inst_list)

np.save('/content/inst.npy', inst_array)

In [10]:
print(len(inst_array), inst_array[:2])

131 [[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0

X = [[2, 1],
     [1, 3],
     [4, 2]]
     
labels = [[1, 0, 1],
          [0, 1, 0],
          [1, 1, 0]]
형태로 변환해서 넣어야 함
330개의 분위기 공간이 존재

In [ ]:
print(dtrain.get_data())  # 데이터 배열 출력
print(dtrain.num_row())  # 데이터의 행 개수 출력
print(dtrain.num_col())  # 데이터의 열 개수 출력
print(labels.shape)
print(dtrain.get_label().shape)  # 라벨 배열 출력
print(131*331)
print(len(np.unique(labels)))

  (0, 0)	-7.275958e-12
  (0, 1)	3.637979e-12
  (0, 2)	-1.0913936e-11
  (0, 3)	3.637979e-12
  (0, 4)	0.0
  (0, 5)	-3.637979e-12
  (0, 6)	-1.0913936e-11
  (0, 7)	3.637979e-12
  (0, 8)	7.275958e-12
  (0, 9)	-3.637979e-12
  (0, 10)	7.275958e-12
  (0, 11)	1.0913936e-11
  (0, 12)	-7.275958e-12
  (0, 13)	1.0913936e-11
  (0, 14)	1.0913936e-11
  (0, 15)	0.0
  (0, 16)	1.0913936e-11
  (0, 17)	0.0
  (0, 18)	1.0913936e-11
  (0, 19)	-3.637979e-12
  (0, 20)	-1.8189894e-11
  (0, 21)	1.0913936e-11
  (0, 22)	-1.0913936e-11
  (0, 23)	7.275958e-12
  (0, 24)	3.637979e-12
  :	:
  (130, 99975)	0.0
  (130, 99976)	0.0
  (130, 99977)	0.0
  (130, 99978)	0.0
  (130, 99979)	0.0
  (130, 99980)	0.0
  (130, 99981)	0.0
  (130, 99982)	0.0
  (130, 99983)	0.0
  (130, 99984)	0.0
  (130, 99985)	0.0
  (130, 99986)	0.0
  (130, 99987)	0.0
  (130, 99988)	0.0
  (130, 99989)	0.0
  (130, 99990)	0.0
  (130, 99991)	0.0
  (130, 99992)	0.0
  (130, 99993)	0.0
  (130, 99994)	0.0
  (130, 99995)	0.0
  (130, 99996)	0.0
  (130, 99997)	0.0


In [8]:
#부분
import numpy as np
#이전에 처리해둔 사전과 전처리 라벨링 가져옴, zip파일 형태 다운
%cd /content/
!gdown 1WyqD20ZMZ_4lwQ7-xutrUu9RLaQk2ElU --output mfcc_test.npy
#https://drive.google.com/file/d/1WyqD20ZMZ_4lwQ7-xutrUu9RLaQk2ElU/view?usp=share_link
!gdown 1mifYHOsThNQhg_T-1xKtkgm66CJQfdYZ --output inst.txt
# https://drive.google.com/file/d/1mifYHOsThNQhg_T-1xKtkgm66CJQfdYZ/view?usp=share_link

/content
Downloading...
From: https://drive.google.com/uc?id=1WyqD20ZMZ_4lwQ7-xutrUu9RLaQk2ElU
To: /content/mfcc_test.npy
100% 2.05M/2.05M [00:00<00:00, 191MB/s]
Downloading...
From: https://drive.google.com/uc?id=1mifYHOsThNQhg_T-1xKtkgm66CJQfdYZ
To: /content/inst.txt
100% 3.25k/3.25k [00:00<00:00, 17.7MB/s]


In [11]:
mfcc_data = np.load('/content/mfcc_test.npy', allow_pickle=True)
labels = np.load('/content/inst.npy', allow_pickle=True)

In [12]:
print(mfcc_data.shape)
print(labels.shape)

(131, 20, 196)
(131, 331)


In [13]:
n_samples = mfcc_data.shape[0]
n_features = mfcc_data.shape[1] * mfcc_data.shape[2]
flattened_data = mfcc_data.reshape(n_samples, n_features)
print(flattened_data.shape)

(131, 3920)


In [14]:
import random

# 같은 인덱스의 서브 리스트들을 추출합니다.
sub_lists = list(zip(flattened_data, labels))

# 추출한 서브 리스트들을 섞습니다.
random.shuffle(sub_lists)

# 섞인 서브 리스트들을 다시 원래 리스트에 삽입합니다.
flattened_data, flattened_labels = zip(*sub_lists)

# 두 개의 리스트의 길이를 구합니다.
length = len(flattened_labels)

# 8:2 비율에 따라 분할할 인덱스를 계산합니다.
split_index = int(length * 0.9)

# 첫 번째 리스트를 분할합니다.
data_train = np.array(flattened_data[:split_index])
data_test = np.array(flattened_data[split_index:])

# 두 번째 리스트를 분할합니다.
labels_train = np.array(flattened_labels[:split_index])
labels_test = np.array(flattened_labels[split_index:])

# 결과를 출력합니다.
print(data_train.shape, data_test.shape)
print(labels_train.shape, labels_test.shape)


(117, 3920) (14, 3920)
(117, 331) (14, 331)


In [16]:
import numpy as np
import xgboost as xgb
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


result = []
# One-vs-Rest (OvR)
for class_index in range(labels.shape[1]):
    # 해당 클래스를 양성 클래스로, 나머지 클래스들을 음성 클래스로 변환
    binary_labels = labels_train[:, class_index]
    if not 1 in binary_labels:
      print()
      print(class_index + 1)
      print()
      continue
    # print(binary_labels)
    dtrain = xgb.DMatrix(data_train, label=binary_labels)

    positive_samples = binary_labels.sum()
    negative_samples = len(binary_labels) - positive_samples

    # scale_pos_weight 값 계산
    scale_pos_weight = negative_samples / positive_samples
    
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'learning_rate': 0.1,
        'scale_pos_weight': scale_pos_weight
    }

    # XGBoost 모델 학습
    xgb_model = xgb.train(params, dtrain, num_boost_round=10)

    
    binary_labels = labels_test[:, class_index]
    print(binary_labels)
    print(sum(binary_labels), len(binary_labels))
    check_train = xgb.DMatrix(data_test, label=binary_labels)
    # 모델 예측
    predictions = xgb_model.predict(check_train)
    print(f"Class {class_index + 1} Predictions:", predictions)
    print(predictions>0.5)

    #모델 평가
    from sklearn.metrics import accuracy_score, log_loss

    # 예측 결과와 실제 레이블을 비교하여 정확도 계산
    accuracy = accuracy_score(binary_labels, predictions > 0.5)
    print(f"Class {class_index + 1} Accuracy:", accuracy)

    # 로그 손실 계산
    logloss = log_loss(binary_labels, predictions)
    print(f"Class {class_index + 1} Log Loss:", logloss)

    
    # 오차 행렬 계산
    cm = confusion_matrix(binary_labels, predictions > 0.5)

    print(cm)

    # 정확도 계산
    accuracy = accuracy_score(binary_labels, predictions > 0.5)

    # 정밀도 계산
    precision = precision_score(binary_labels, predictions > 0.5)

    # 재현율 계산
    recall = recall_score(binary_labels, predictions > 0.5)

    # F1 스코어 계산
    f1 = f1_score(binary_labels, predictions > 0.5)

    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1 Score:", f1)

    result.append([class_index + 1, accuracy, logloss, cm, accuracy, precision, recall, f1])

    
    # # 모델 저장
    # model_path = f'/content/drive/MyDrive/xgb_model{class_index + 1}.bin'
    # xgb_model.save_model(model_path)

    
    # 모델 저장
    model_path = f'/content/xgb_model{class_index + 1}.bin'
    xgb_model.save_model(model_path)
    from google.colab import files

    files.download(f'/content/xgb_model{class_index + 1}.bin')


1

[1 0 0 0 0 1 0 0 1 1 0 0 0 0]
4 14
Class 2 Predictions: [0.39731333 0.23455685 0.45045504 0.5675596  0.196248   0.39183605
 0.68855566 0.5586913  0.6207594  0.54878646 0.5291611  0.20398755
 0.20398755 0.26400417]
[False False False  True False False  True  True  True  True  True False
 False False]
Class 2 Accuracy: 0.5714285714285714
Class 2 Log Loss: 0.597152575062305
[[6 4]
 [2 2]]
Accuracy: 0.5714285714285714
Precision: 0.3333333333333333
Recall: 0.5
F1 Score: 0.4


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[1 1 0 1 0 1 1 1 1 1 1 0 0 1]
10 14
Class 3 Predictions: [0.52890015 0.7984476  0.623854   0.61454165 0.49342972 0.40326744
 0.77473927 0.7984476  0.3620307  0.7506129  0.7984476  0.30921564
 0.3366594  0.7984476 ]
[ True  True  True  True False False  True  True False  True  True False
 False  True]
Class 3 Accuracy: 0.7857142857142857
Class 3 Log Loss: 0.49490841278970255
[[3 1]
 [2 8]]
Accuracy: 0.7857142857142857
Precision: 0.8888888888888888
Recall: 0.8
F1 Score: 0.8421052631578948


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


4


5


6


7


8

[1 0 0 0 0 1 0 0 1 1 0 0 0 0]
4 14
Class 9 Predictions: [0.39731333 0.23455685 0.45045504 0.5675596  0.196248   0.39183605
 0.68855566 0.5586913  0.6207594  0.54878646 0.5291611  0.20398755
 0.20398755 0.26400417]
[False False False  True False False  True  True  True  True  True False
 False False]
Class 9 Accuracy: 0.5714285714285714
Class 9 Log Loss: 0.597152575062305
[[6 4]
 [2 2]]
Accuracy: 0.5714285714285714
Precision: 0.3333333333333333
Recall: 0.5
F1 Score: 0.4


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


10

[0 0 1 0 1 0 0 0 0 0 0 1 1 0]
4 14
Class 11 Predictions: [0.589319   0.19238074 0.27400047 0.3150614  0.5939202  0.56793845
 0.21947677 0.19238074 0.48819762 0.2165708  0.19238074 0.7468235
 0.41855085 0.19238074]
[ True False False False  True  True False False False False False  True
 False False]
Class 11 Accuracy: 0.7142857142857143
Class 11 Log Loss: 0.507315077664361
[[8 2]
 [2 2]]
Accuracy: 0.7142857142857143
Precision: 0.5
Recall: 0.5
F1 Score: 0.5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


12

[0 1 0 1 0 0 1 1 0 0 1 0 0 1]
6 14
Class 13 Predictions: [0.55953413 0.7826041  0.75818515 0.47748792 0.18961276 0.18961276
 0.53658235 0.6987697  0.7224659  0.18961276 0.56602216 0.24555703
 0.21021973 0.5998425 ]
[ True  True  True False False False  True  True  True False  True False
 False  True]
Class 13 Accuracy: 0.7142857142857143
Class 13 Log Loss: 0.5510961540032
[[5 3]
 [1 5]]
Accuracy: 0.7142857142857143
Precision: 0.625
Recall: 0.8333333333333334
F1 Score: 0.7142857142857143


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


14


15

[0 1 0 1 0 0 1 1 0 0 1 0 0 1]
6 14
Class 16 Predictions: [0.55953413 0.7826041  0.75818515 0.47748792 0.18961276 0.18961276
 0.53658235 0.6987697  0.7224659  0.18961276 0.56602216 0.24555703
 0.21021973 0.5998425 ]
[ True  True  True False False False  True  True  True False  True False
 False  True]
Class 16 Accuracy: 0.7142857142857143
Class 16 Log Loss: 0.5510961540032
[[5 3]
 [1 5]]
Accuracy: 0.7142857142857143
Precision: 0.625
Recall: 0.8333333333333334
F1 Score: 0.7142857142857143


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0 0 1 0 1 0 0 0 0 0 0 1 1 0]
4 14
Class 17 Predictions: [0.589319   0.19238074 0.27400047 0.3150614  0.5939202  0.56793845
 0.21947677 0.19238074 0.48819762 0.2165708  0.19238074 0.7468235
 0.41855085 0.19238074]
[ True False False False  True  True False False False False False  True
 False False]
Class 17 Accuracy: 0.7142857142857143
Class 17 Log Loss: 0.507315077664361
[[8 2]
 [2 2]]
Accuracy: 0.7142857142857143
Precision: 0.5
Recall: 0.5
F1 Score: 0.5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[1 0 1 0 1 1 0 0 1 1 0 1 1 0]
8 14
Class 18 Predictions: [0.5557449  0.21007493 0.38697454 0.6160638  0.7508509  0.70798594
 0.46920225 0.24080804 0.33614948 0.7339111  0.38685697 0.76998997
 0.7257585  0.4736414 ]
[ True False False  True  True  True False False False  True False  True
  True False]
Class 18 Accuracy: 0.7857142857142857
Class 18 Log Loss: 0.5273645990006531
[[5 1]
 [2 6]]
Accuracy: 0.7857142857142857
Precision: 0.8571428571428571
Recall: 0.75
F1 Score: 0.7999999999999999


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


19


20

[1 0 0 0 0 1 0 0 1 1 0 0 0 0]
4 14
Class 21 Predictions: [0.39731333 0.23455685 0.45045504 0.5675596  0.196248   0.39183605
 0.68855566 0.5586913  0.6207594  0.54878646 0.5291611  0.20398755
 0.20398755 0.26400417]
[False False False  True False False  True  True  True  True  True False
 False False]
Class 21 Accuracy: 0.5714285714285714
Class 21 Log Loss: 0.597152575062305
[[6 4]
 [2 2]]
Accuracy: 0.5714285714285714
Precision: 0.3333333333333333
Recall: 0.5
F1 Score: 0.4


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


22


23


24


25

[0 0 1 0 1 0 0 0 0 0 0 1 1 0]
4 14
Class 26 Predictions: [0.589319   0.19238074 0.27400047 0.3150614  0.5939202  0.56793845
 0.21947677 0.19238074 0.48819762 0.2165708  0.19238074 0.7468235
 0.41855085 0.19238074]
[ True False False False  True  True False False False False False  True
 False False]
Class 26 Accuracy: 0.7142857142857143
Class 26 Log Loss: 0.507315077664361
[[8 2]
 [2 2]]
Accuracy: 0.7142857142857143
Precision: 0.5
Recall: 0.5
F1 Score: 0.5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0 0 1 0 1 0 0 0 0 0 0 1 1 0]
4 14
Class 27 Predictions: [0.589319   0.19238074 0.27400047 0.3150614  0.5939202  0.56793845
 0.21947677 0.19238074 0.48819762 0.2165708  0.19238074 0.7468235
 0.41855085 0.19238074]
[ True False False False  True  True False False False False False  True
 False False]
Class 27 Accuracy: 0.7142857142857143
Class 27 Log Loss: 0.507315077664361
[[8 2]
 [2 2]]
Accuracy: 0.7142857142857143
Precision: 0.5
Recall: 0.5
F1 Score: 0.5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


28


29

[0 1 0 1 0 0 1 1 0 0 1 0 0 1]
6 14
Class 30 Predictions: [0.55953413 0.7826041  0.75818515 0.47748792 0.18961276 0.18961276
 0.53658235 0.6987697  0.7224659  0.18961276 0.56602216 0.24555703
 0.21021973 0.5998425 ]
[ True  True  True False False False  True  True  True False  True False
 False  True]
Class 30 Accuracy: 0.7142857142857143
Class 30 Log Loss: 0.5510961540032
[[5 3]
 [1 5]]
Accuracy: 0.7142857142857143
Precision: 0.625
Recall: 0.8333333333333334
F1 Score: 0.7142857142857143


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


31


32


33


34

[0 0 1 0 1 0 0 0 0 0 0 1 1 0]
4 14
Class 35 Predictions: [0.589319   0.19238074 0.27400047 0.3150614  0.5939202  0.56793845
 0.21947677 0.19238074 0.48819762 0.2165708  0.19238074 0.7468235
 0.41855085 0.19238074]
[ True False False False  True  True False False False False False  True
 False False]
Class 35 Accuracy: 0.7142857142857143
Class 35 Log Loss: 0.507315077664361
[[8 2]
 [2 2]]
Accuracy: 0.7142857142857143
Precision: 0.5
Recall: 0.5
F1 Score: 0.5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


36


37


38


39


40

[0 1 0 1 0 0 1 1 0 0 1 0 0 1]
6 14
Class 41 Predictions: [0.55953413 0.7826041  0.75818515 0.47748792 0.18961276 0.18961276
 0.53658235 0.6987697  0.7224659  0.18961276 0.56602216 0.24555703
 0.21021973 0.5998425 ]
[ True  True  True False False False  True  True  True False  True False
 False  True]
Class 41 Accuracy: 0.7142857142857143
Class 41 Log Loss: 0.5510961540032
[[5 3]
 [1 5]]
Accuracy: 0.7142857142857143
Precision: 0.625
Recall: 0.8333333333333334
F1 Score: 0.7142857142857143


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


42


43


44


45


46


47


48


49


50


51


52


53


54


55


56


57


58


59


60


61


62


63


64


65


66

[0 1 0 1 0 0 1 1 0 0 1 0 0 1]
6 14
Class 67 Predictions: [0.55953413 0.7826041  0.75818515 0.47748792 0.18961276 0.18961276
 0.53658235 0.6987697  0.7224659  0.18961276 0.56602216 0.24555703
 0.21021973 0.5998425 ]
[ True  True  True False False False  True  True  True False  True False
 False  True]
Class 67 Accuracy: 0.7142857142857143
Class 67 Log Loss: 0.5510961540032
[[5 3]
 [1 5]]
Accuracy: 0.7142857142857143
Precision: 0.625
Recall: 0.8333333333333334
F1 Score: 0.7142857142857143


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


68

[1 0 1 0 1 1 0 0 1 1 0 1 1 0]
8 14
Class 69 Predictions: [0.5557449  0.21007493 0.38697454 0.6160638  0.7508509  0.70798594
 0.46920225 0.24080804 0.33614948 0.7339111  0.38685697 0.76998997
 0.7257585  0.4736414 ]
[ True False False  True  True  True False False False  True False  True
  True False]
Class 69 Accuracy: 0.7857142857142857
Class 69 Log Loss: 0.5273645990006531
[[5 1]
 [2 6]]
Accuracy: 0.7857142857142857
Precision: 0.8571428571428571
Recall: 0.75
F1 Score: 0.7999999999999999


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0 0 1 0 1 0 0 0 0 0 0 1 1 0]
4 14
Class 70 Predictions: [0.589319   0.19238074 0.27400047 0.3150614  0.5939202  0.56793845
 0.21947677 0.19238074 0.48819762 0.2165708  0.19238074 0.7468235
 0.41855085 0.19238074]
[ True False False False  True  True False False False False False  True
 False False]
Class 70 Accuracy: 0.7142857142857143
Class 70 Log Loss: 0.507315077664361
[[8 2]
 [2 2]]
Accuracy: 0.7142857142857143
Precision: 0.5
Recall: 0.5
F1 Score: 0.5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0 0 1 0 1 0 0 0 0 0 0 1 1 0]
4 14
Class 71 Predictions: [0.589319   0.19238074 0.27400047 0.3150614  0.5939202  0.56793845
 0.21947677 0.19238074 0.48819762 0.2165708  0.19238074 0.7468235
 0.41855085 0.19238074]
[ True False False False  True  True False False False False False  True
 False False]
Class 71 Accuracy: 0.7142857142857143
Class 71 Log Loss: 0.507315077664361
[[8 2]
 [2 2]]
Accuracy: 0.7142857142857143
Precision: 0.5
Recall: 0.5
F1 Score: 0.5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0 0 1 0 1 0 0 0 0 0 0 1 1 0]
4 14
Class 72 Predictions: [0.589319   0.19238074 0.27400047 0.3150614  0.5939202  0.56793845
 0.21947677 0.19238074 0.48819762 0.2165708  0.19238074 0.7468235
 0.41855085 0.19238074]
[ True False False False  True  True False False False False False  True
 False False]
Class 72 Accuracy: 0.7142857142857143
Class 72 Log Loss: 0.507315077664361
[[8 2]
 [2 2]]
Accuracy: 0.7142857142857143
Precision: 0.5
Recall: 0.5
F1 Score: 0.5


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0 1 0 1 0 0 1 1 0 0 1 0 0 1]
6 14
Class 73 Predictions: [0.55953413 0.7826041  0.75818515 0.47748792 0.18961276 0.18961276
 0.53658235 0.6987697  0.7224659  0.18961276 0.56602216 0.24555703
 0.21021973 0.5998425 ]
[ True  True  True False False False  True  True  True False  True False
 False  True]
Class 73 Accuracy: 0.7142857142857143
Class 73 Log Loss: 0.5510961540032
[[5 3]
 [1 5]]
Accuracy: 0.7142857142857143
Precision: 0.625
Recall: 0.8333333333333334
F1 Score: 0.7142857142857143


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[0 1 0 1 0 0 1 1 0 0 1 0 0 1]
6 14
Class 74 Predictions: [0.55953413 0.7826041  0.75818515 0.47748792 0.18961276 0.18961276
 0.53658235 0.6987697  0.7224659  0.18961276 0.56602216 0.24555703
 0.21021973 0.5998425 ]
[ True  True  True False False False  True  True  True False  True False
 False  True]
Class 74 Accuracy: 0.7142857142857143
Class 74 Log Loss: 0.5510961540032
[[5 3]
 [1 5]]
Accuracy: 0.7142857142857143
Precision: 0.625
Recall: 0.8333333333333334
F1 Score: 0.7142857142857143


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[1 0 0 0 0 1 0 0 1 1 0 0 0 0]
4 14
Class 75 Predictions: [0.39731333 0.23455685 0.45045504 0.5675596  0.196248   0.39183605
 0.68855566 0.5586913  0.6207594  0.54878646 0.5291611  0.20398755
 0.20398755 0.26400417]
[False False False  True False False  True  True  True  True  True False
 False False]
Class 75 Accuracy: 0.5714285714285714
Class 75 Log Loss: 0.597152575062305
[[6 4]
 [2 2]]
Accuracy: 0.5714285714285714
Precision: 0.3333333333333333
Recall: 0.5
F1 Score: 0.4


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>


76


77


78


79


80


81


82


83


84


85


86


87


88


89


90


91


92


93


94


95


96


97


98


99


100


101


102


103


104


105


106


107


108


109


110


111


112


113


114


115


116


117


118


119


120


121


122


123


124


125


126


127


128


129


130


131


132


133


134


135


136


137


138


139


140


141


142


143


144


145


146


147


148


149


150


151


152


153


154


155


156


157


158


159


160


161


162


163


164


165


166


167


168


169


170


171


172


173


174


175


176


177


178


179


180


181


182


183


184


185


186


187


188


189


190


191


192


193


194


195


196


197


198


199


200


201


202


203


204


205


206


207


208


209


210


211


212


213


214


215


216


217


218


219


220


221


222


223


224


225


226


227


228


229


230


231


232


233


234


235


236


237


238


239


240


241


242


243


244


245


246

In [17]:
# F1 스코어 계산
print(f1_score(binary_labels, predictions > 0.3))
print(f1_score(binary_labels, predictions > 0.4))
print(f1_score(binary_labels, predictions > 0.5))
print(f1_score(binary_labels, predictions > 0.6))
print(f1_score(binary_labels, predictions > 0.7))
print(f1_score(binary_labels, predictions > 0.8))



ValueError: ignored

In [ ]:

accuracy = accuracy_score(binary_labels, predictions > 0.3)
print(f"Class {class_index + 1} Accuracy:", accuracy)

accuracy = accuracy_score(binary_labels, predictions > 0.4)
print(f"Class {class_index + 1} Accuracy:", accuracy)

accuracy = accuracy_score(binary_labels, predictions > 0.5)
print(f"Class {class_index + 1} Accuracy:", accuracy)


accuracy = accuracy_score(binary_labels, predictions > 0.6)
print(f"Class {class_index + 1} Accuracy:", accuracy)

accuracy = accuracy_score(binary_labels, predictions > 0.7)
print(f"Class {class_index + 1} Accuracy:", accuracy)

Class 1 Accuracy: 0.6
Class 1 Accuracy: 0.6764705882352942
Class 1 Accuracy: 0.7588235294117647
Class 1 Accuracy: 0.788235294117647
Class 1 Accuracy: 0.8058823529411765


In [19]:
for elem in result:
  print(elem[-1])

0.4
0.8421052631578948
0.4
0.5
0.7142857142857143
0.7142857142857143
0.5
0.7999999999999999
0.4
0.5
0.5
0.7142857142857143
0.5
0.7142857142857143
0.7142857142857143
0.7999999999999999
0.5
0.5
0.5
0.7142857142857143
0.7142857142857143
0.4


In [ ]:
with open('list.txt', 'w') as file:
    for item in result:
        file.write(item + '\n')
files.download(f'/content/list.txt')

In [ ]:
total = 0
for elem in result:
  total += elem[1]
total /= len(result)
print(total)

0.8147058823529412


In [ ]:

# Classifier Chains
chain_labels = np.zeros_like(labels)

for class_index in range(labels.shape[1]):
    # 이전 분류기의 출력을 현재 데이터에 추가
    chain_data = np.concatenate((data, chain_labels[:, :class_index]), axis=1)
    
    # 현재 클래스를 예측하기 위한 이진 라벨
    binary_labels = labels[:, class_index]
    dtrain = xgb.DMatrix(chain_data, label=binary_labels)
    
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'learning_rate': 0.1,
        'max_depth': 3
    }

    # XGBoost 모델 학습
    xgb_model = xgb.train(params, dtrain, num_boost_round=10)
    
    # 모델 예측
    predictions = xgb_model.predict(dtrain)
    print(f"Class {class_index + 1} Predictions:", predictions)
    
    # 현재 클래스의 예측값을 chain_labels에 업데이트
    chain_labels[:, class_index] = predictions.round()

print("Final Predictions (Classifier Chains):", chain_labels)


In [ ]:

params = {
    'objective': 'multi:softmax',  # 다중 라벨 문제의 손실 함수 설정
    'num_class': 331,   # 클래스의 개수 설정
    'eval_metric': 'merror',      # 평가 지표 설정
    'learning_rate': 0.1,           # 학습률 설정
    'max_depth': 3                  # 트리의 최대 깊이 설정
}

# XGBoost 모델 학습
xgb_model = xgb.train(params, dtrain, num_boost_round=10)


XGBoostError: ignored

In [ ]:

# 모델 저장
model_path = '/content/drive/MyDrive/xgb_model.bin'
xgb_model.save_model(model_path)

In [ ]:

# 모델 저장
model_path = '/content/xgb_model.bin'
xgb_model.save_model(model_path)
from google.colab import files

files.download('/content/xgb_model.bin')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# test_data = np.load('/path/to/test_data.npy', allow_pickle=True)
# test_labels = np.load('/path/to/test_labels.npy', allow_pickle=True)
# test_data = np.vstack(test_data)  # 데이터를 적절한 형태로 구성 (2차원 배열)
# test_labels = np.vstack(test_labels)  # 레이블을 적절한 형태로 구성 (2차원 배열)

# # 테스트 데이터를 DMatrix로 변환
# dtest = xgb.DMatrix(test_data)

# 모델 예측
predictions = xgb_model.predict(dtrain)
# print(dtrain.get_data())
print(predictions)
# 예측 결과 평가
# from sklearn.metrics import accuracy_score
# for elem in predictions:
#   for i in range(len(elem)):
#     elem[i] = 1 if elem[i] >= 0.8 else 0
# print(predictions[0])
# accuracy = accuracy_score(labels, predictions)
# print("테스트 정확도:", accuracy)

[0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452 0.1859452
 0.185

In [ ]:
print(labels[0])

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:

print(predictions[0])

[0.02855972 0.08450808 0.05115506 0.02855972 0.02855972 0.02855972
 0.02855972 0.02855972 0.08450808 0.02855972 0.9488449  0.02855972
 0.05553409 0.02855972 0.02855972 0.05553409 0.9488449  0.9444659
 0.02855972 0.02855972 0.08450808 0.02855972 0.02855972 0.02855972
 0.02855972 0.9488449  0.9488449  0.02855972 0.02855972 0.05553409
 0.02855972 0.02855972 0.02855972 0.02855972 0.9488449  0.02855972
 0.02855972 0.02855972 0.02855972 0.02855972 0.05553409 0.02855972
 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972
 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972
 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972
 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972
 0.05553409 0.02855972 0.9444659  0.9488449  0.9488449  0.9488449
 0.05553409 0.05553409 0.08450808 0.02855972 0.02855972 0.02855972
 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972
 0.02855972 0.02855972 0.02855972 0.02855972 0.02855972 0.028559